// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.15.8
// source: ccmesh.proto

package ccmesh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mesh_HealthCheck_FullMethodName     = "/ccmesh.Mesh/HealthCheck"
	Mesh_ClientRead_FullMethodName      = "/ccmesh.Mesh/ClientRead"
	Mesh_ClientWrite_FullMethodName     = "/ccmesh.Mesh/ClientWrite"
	Mesh_ServerWrite_FullMethodName     = "/ccmesh.Mesh/ServerWrite"
	Mesh_ClientCommitTxn_FullMethodName = "/ccmesh.Mesh/ClientCommitTxn"
	Mesh_ServerCommitTxn_FullMethodName = "/ccmesh.Mesh/ServerCommitTxn"
)

// MeshClient is the client API for Mesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeshClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	ClientRead(ctx context.Context, in *ClientReadRequest, opts ...grpc.CallOption) (*ClientReadResponse, error)
	ClientWrite(ctx context.Context, in *ClientWriteRequest, opts ...grpc.CallOption) (*ClientWriteResponse, error)
	ServerWrite(ctx context.Context, in *ServerWriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ClientCommitTxn(ctx context.Context, in *ClientCommitTxnRequest, opts ...grpc.CallOption) (*ClientCommitTxnResponse, error)
	ServerCommitTxn(ctx context.Context, in *ServerCommitTxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type meshClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshClient(cc grpc.ClientConnInterface) MeshClient {
	return &meshClient{cc}
}

func (c *meshClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Mesh_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) ClientRead(ctx context.Context, in *ClientReadRequest, opts ...grpc.CallOption) (*ClientReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientReadResponse)
	err := c.cc.Invoke(ctx, Mesh_ClientRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) ClientWrite(ctx context.Context, in *ClientWriteRequest, opts ...grpc.CallOption) (*ClientWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientWriteResponse)
	err := c.cc.Invoke(ctx, Mesh_ClientWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) ServerWrite(ctx context.Context, in *ServerWriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Mesh_ServerWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) ClientCommitTxn(ctx context.Context, in *ClientCommitTxnRequest, opts ...grpc.CallOption) (*ClientCommitTxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientCommitTxnResponse)
	err := c.cc.Invoke(ctx, Mesh_ClientCommitTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshClient) ServerCommitTxn(ctx context.Context, in *ServerCommitTxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Mesh_ServerCommitTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServer is the server API for Mesh service.
// All implementations must embed UnimplementedMeshServer
// for forward compatibility.
type MeshServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	ClientRead(context.Context, *ClientReadRequest) (*ClientReadResponse, error)
	ClientWrite(context.Context, *ClientWriteRequest) (*ClientWriteResponse, error)
	ServerWrite(context.Context, *ServerWriteRequest) (*emptypb.Empty, error)
	ClientCommitTxn(context.Context, *ClientCommitTxnRequest) (*ClientCommitTxnResponse, error)
	ServerCommitTxn(context.Context, *ServerCommitTxnRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMeshServer()
}

// UnimplementedMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServer struct{}

func (UnimplementedMeshServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMeshServer) ClientRead(context.Context, *ClientReadRequest) (*ClientReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientRead not implemented")
}
func (UnimplementedMeshServer) ClientWrite(context.Context, *ClientWriteRequest) (*ClientWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientWrite not implemented")
}
func (UnimplementedMeshServer) ServerWrite(context.Context, *ServerWriteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerWrite not implemented")
}
func (UnimplementedMeshServer) ClientCommitTxn(context.Context, *ClientCommitTxnRequest) (*ClientCommitTxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientCommitTxn not implemented")
}
func (UnimplementedMeshServer) ServerCommitTxn(context.Context, *ServerCommitTxnRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerCommitTxn not implemented")
}
func (UnimplementedMeshServer) mustEmbedUnimplementedMeshServer() {}
func (UnimplementedMeshServer) testEmbeddedByValue()              {}

// UnsafeMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServer will
// result in compilation errors.
type UnsafeMeshServer interface {
	mustEmbedUnimplementedMeshServer()
}

func RegisterMeshServer(s grpc.ServiceRegistrar, srv MeshServer) {
	// If the following call panics, it indicates UnimplementedMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mesh_ServiceDesc, srv)
}

func _Mesh_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_ClientRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).ClientRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_ClientRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).ClientRead(ctx, req.(*ClientReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_ClientWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).ClientWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_ClientWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).ClientWrite(ctx, req.(*ClientWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_ServerWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).ServerWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_ServerWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).ServerWrite(ctx, req.(*ServerWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_ClientCommitTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientCommitTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).ClientCommitTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_ClientCommitTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).ClientCommitTxn(ctx, req.(*ClientCommitTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mesh_ServerCommitTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerCommitTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).ServerCommitTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_ServerCommitTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).ServerCommitTxn(ctx, req.(*ServerCommitTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mesh_ServiceDesc is the grpc.ServiceDesc for Mesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ccmesh.Mesh",
	HandlerType: (*MeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Mesh_HealthCheck_Handler,
		},
		{
			MethodName: "ClientRead",
			Handler:    _Mesh_ClientRead_Handler,
		},
		{
			MethodName: "ClientWrite",
			Handler:    _Mesh_ClientWrite_Handler,
		},
		{
			MethodName: "ServerWrite",
			Handler:    _Mesh_ServerWrite_Handler,
		},
		{
			MethodName: "ClientCommitTxn",
			Handler:    _Mesh_ClientCommitTxn_Handler,
		},
		{
			MethodName: "ServerCommitTxn",
			Handler:    _Mesh_ServerCommitTxn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ccmesh.proto",
}
